language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then cd test && python -m SimpleHTTPServer; fi &
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then cd test && python -m http.server ; fi &
script:
  - python webpreview/test.py
